In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from package.RankAMIP.logistic import run_logistic_regression
from package.RankAMIP.data_script import make_BT_design_matrix
from package.RankAMIP.logistic import LogisticAMIP
from package.RankAMIP.logistic import find_closest_matchups
from package.RankAMIP.logistic import isRankingRobust
from package.RankAMIP.plot_util import *

### Is ChatBot Arena Data Robust?

### Load Data.

In [2]:
# Import datasets from https://huggingface.co/datasets/lmarena-ai/arena-human-preference-55k
from datasets import load_dataset
ds = load_dataset("lmarena-ai/arena-human-preference-55k")

/Users/JennyH/Library/Python/3.8/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# inspect the available splits
print(ds)  
# grab the ‘train’ split
train = ds["train"]

DatasetDict({
    train: Dataset({
        features: ['id', 'model_a', 'model_b', 'prompt', 'response_a', 'response_b', 'winner_model_a', 'winner_model_b', 'winner_tie'],
        num_rows: 57477
    })
})

In [4]:
df = train.to_pandas()
df.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie
0,30192,gpt-4-1106-preview,gpt-4-0613,"[""Is it morally right to try to have a certain...","[""The question of whether it is morally right ...","[""As an AI, I don't have personal beliefs or o...",1,0,0
1,53567,koala-13b,gpt-4-0613,"[""What is the difference between marriage lice...","[""A marriage license is a legal document that ...","[""A marriage license and a marriage certificat...",0,1,0
2,65089,gpt-3.5-turbo-0613,mistral-medium,"[""explain function calling. how would you call...","[""Function calling is the process of invoking ...","[""Function calling is the process of invoking ...",0,0,1
3,96401,llama-2-13b-chat,mistral-7b-instruct,"[""How can I create a test set for a very rare ...","[""Creating a test set for a very rare category...","[""When building a classifier for a very rare c...",1,0,0
4,198779,koala-13b,gpt-3.5-turbo-0314,"[""What is the best way to travel from Tel-Aviv...","[""The best way to travel from Tel Aviv to Jeru...","[""The best way to travel from Tel-Aviv to Jeru...",0,1,0

In [5]:
df.shape

(57477, 9)

In [6]:
# how to get the unique names in both columns
model_a_names = df['model_a'].unique()
model_b_names = df['model_b'].unique()
# combine the two arrays and get the unique names
model_names = np.unique(np.concatenate((model_a_names, model_b_names)))
# print the number of unique model names
print(f"Number of unique model names: {len(model_names)}")

Number of unique model names: 64

In [56]:
ties = df[df['winner_tie'] == 1]
print(f"Number of ties: {len(ties)}")
# proportion of ties.
print(f"Proportion of ties: {len(ties) / len(df):.2%}")

Number of ties: 17761
Proportion of ties: 30.90%

#### Keep ties.

In [7]:
# drop rows in df with df['winner_tie'] == 1
rawBT = df[['model_a', 'model_b', 'winner_model_a', 'winner_tie']]
rawBT.head()

              model_a              model_b  winner_model_a  winner_tie
0  gpt-4-1106-preview           gpt-4-0613               1           0
1           koala-13b           gpt-4-0613               0           0
2  gpt-3.5-turbo-0613       mistral-medium               0           1
3    llama-2-13b-chat  mistral-7b-instruct               1           0
4           koala-13b   gpt-3.5-turbo-0314               0           0

In [ ]:
# to test robustness upon filtering out these models (do not run this cell).
# rawBT = rawBT[~((rawBT['model_a'].isin(['gpt-4-1106-preview', 'gpt-4-0314', 'gpt-4-0613', 'qwen1.5-72b-chat', 'mistral-medium', 'claude-1', 'claude-2.0', 'gemini-pro-dev-api', 'yi-34b-chat'])) | 
#                 (rawBT['model_b'].isin(['gpt-4-1106-preview', 'gpt-4-0314', 'gpt-4-0613', 'qwen1.5-72b-chat', 'mistral-medium', 'claude-1', 'claude-2.0', 'gemini-pro-dev-api', 'yi-34b-chat'])))]

In [8]:
for model in model_names:
    filtered = rawBT[
        (rawBT['model_a'] == model) | 
        (rawBT['model_b'] == model)
    ]
    print(f"{model}: {filtered.shape[0]}")

RWKV-4-Raven-14B: 1158
alpaca-13b: 1403
chatglm-6b: 1261
chatglm2-6b: 564
chatglm3-6b: 989
claude-1: 3978
claude-2.0: 2456
claude-2.1: 5583
claude-instant-1: 4136
codellama-34b-instruct: 1474
deepseek-llm-67b-chat: 795
dolly-v2-12b: 800
dolphin-2.2.1-mistral-7b: 373
falcon-180b-chat: 286
fastchat-t5-3b: 1021
gemini-pro: 1438
gemini-pro-dev-api: 1486
gpt-3.5-turbo-0125: 861
gpt-3.5-turbo-0314: 1302
gpt-3.5-turbo-0613: 7083
gpt-3.5-turbo-1106: 3352
gpt-4-0125-preview: 1160
gpt-4-0314: 4122
gpt-4-0613: 6165
gpt-4-1106-preview: 7387
gpt4all-13b-snoozy: 408
guanaco-33b: 684
koala-13b: 1598
llama-13b: 547
llama-2-13b-chat: 2607
llama-2-70b-chat: 3428
llama-2-7b-chat: 1793
llama2-70b-steerlm-chat: 667
mistral-7b-instruct: 1617
mistral-7b-instruct-v0.2: 100
mistral-medium: 3315
mixtral-8x7b-instruct-v0.1: 3545
mpt-30b-chat: 598
mpt-7b-chat: 928
nous-hermes-2-mixtral-8x7b-dpo: 325
oasst-pythia-12b: 1494
openchat-3.5: 1632
openchat-3.5-0106: 244
openhermes-2.5-mistral-7b: 952
palm-2: 1977
pplx-70b-online: 1420
pplx-7b-online: 1250
qwen-14b-chat: 1072
qwen1.5-4b-chat: 200
qwen1.5-72b-chat: 551
qwen1.5-7b-chat: 208
solar-10.7b-instruct-v1.0: 899
stablelm-tuned-alpha-7b: 771
starling-lm-7b-alpha: 1134
stripedhyena-nous-7b: 914
tulu-2-dpo-70b: 1200
vicuna-13b: 3448
vicuna-33b: 3720
vicuna-7b: 1591
wizardlm-13b: 1580
wizardlm-70b: 1644
yi-34b-chat: 1447
zephyr-7b-alpha: 412
zephyr-7b-beta: 2401

In [9]:
# make weighted design matrix for BT.
X, y, player_to_id = make_BT_design_matrix(rawBT, weight_tie = True)
X.shape, y.shape

((114954, 63), (114954,))

In [ ]:
# import pickle
# with open('bt_data.pkl', 'wb') as f:
#     pickle.dump((X, y), f)

In [ ]:
# # Results upon removing players 2 through 10 in the dataset.
# with open('results/ChatbotArenaNonrobustWtd.pkl', 'rb') as f:
#     cba_results = pickle.load(f)
# cba_results

{(1, 2): (21,
  None,
  -0.004146461884523535,
  0.002200252892290602,
  array([46259,  6212])),
 (3, 29): (6,
  61,
  0.7214777505716051,
  -0.026849342132582388,
  array([26551, 17137, 40808, 32585,  3046, 11617, 39409, 39779, 33011,
         56011, 24859, 28859, 48893, 17324, 38734, 13179, 18149, 34968,
         37289, 20538,  1308,  5210, 23104, 49522,  7020, 46358, 27533,
         48536, 40704])),
 (5, 3): (41,
  47,
  0.01376073850843107,
  -0.001148770551445799,
  array([20425, 38755, 13835])),
 (10, 1): (5,
  4,
  0.0008246616768733395,
  -0.0012153237089130853,
  array([24811])),
 (20, 1): (35,
  48,
  0.007468269893045054,
  -0.0006298890499366605,
  array([5389]))}

In [10]:
id_to_player = {v: k for k, v in player_to_id.items()}
id_to_player

{0: 'gpt-4-1106-preview',
 1: 'koala-13b',
 2: 'gpt-3.5-turbo-0613',
 3: 'llama-2-13b-chat',
 4: 'vicuna-13b',
 5: 'mixtral-8x7b-instruct-v0.1',
 6: 'gemini-pro',
 7: 'gpt-4-0314',
 8: 'vicuna-7b',
 9: 'chatglm3-6b',
 10: 'pplx-70b-online',
 11: 'mpt-30b-chat',
 12: 'llama2-70b-steerlm-chat',
 13: 'claude-1',
 14: 'claude-2.1',
 15: 'chatglm-6b',
 16: 'claude-instant-1',
 17: 'dolly-v2-12b',
 18: 'claude-2.0',
 19: 'deepseek-llm-67b-chat',
 20: 'openchat-3.5',
 21: 'starling-lm-7b-alpha',
 22: 'gpt-4-0125-preview',
 23: 'llama-2-7b-chat',
 24: 'gpt-4-0613',
 25: 'wizardlm-70b',
 26: 'stablelm-tuned-alpha-7b',
 27: 'vicuna-33b',
 28: 'chatglm2-6b',
 29: 'dolphin-2.2.1-mistral-7b',
 30: 'llama-2-70b-chat',
 31: 'llama-13b',
 32: 'palm-2',
 33: 'wizardlm-13b',
 34: 'codellama-34b-instruct',
 35: 'gemini-pro-dev-api',
 36: 'gpt-3.5-turbo-0314',
 37: 'gpt-3.5-turbo-1106',
 38: 'yi-34b-chat',
 39: 'oasst-pythia-12b',
 40: 'qwen-14b-chat',
 41: 'alpaca-13b',
 42: 'qwen1.5-72b-chat',
 43: 'gpt-3.5-turbo-0125',
 44: 'pplx-7b-online',
 45: 'qwen1.5-4b-chat',
 46: 'fastchat-t5-3b',
 47: 'solar-10.7b-instruct-v1.0',
 48: 'mistral-medium',
 49: 'nous-hermes-2-mixtral-8x7b-dpo',
 50: 'zephyr-7b-beta',
 51: 'openhermes-2.5-mistral-7b',
 52: 'mistral-7b-instruct',
 53: 'tulu-2-dpo-70b',
 54: 'mpt-7b-chat',
 55: 'zephyr-7b-alpha',
 56: 'qwen1.5-7b-chat',
 57: 'RWKV-4-Raven-14B',
 58: 'guanaco-33b',
 59: 'stripedhyena-nous-7b',
 60: 'gpt4all-13b-snoozy',
 61: 'falcon-180b-chat',
 62: 'mistral-7b-instruct-v0.2',
 63: 'openchat-3.5-0106'}

#### Run Top-k Robustness Check.

In [11]:
ks = [1] # 2
results = {}
for k in ks:
    alphaN = 1
    chatbotA = -1
    while chatbotA == -1:
        chatbotA, chatbotB, chatbotOriginalBetaDiff, chatNewBetaDiff, chatIndices = isRankingRobust(k, alphaN, X, y, weighted = True)
        results[(k, alphaN)] = (chatbotA, chatbotB, chatbotOriginalBetaDiff, chatNewBetaDiff, chatIndices)
        alphaN += 1
        print(alphaN)

2
3

Plot arena BT-scores.

In [13]:
rankings = return_rankings_list(X, y, results, 1, 2, player_to_id)

In [12]:
results_nonrobust = {k: v for k, v in results.items() if v[0] != -1}
results_nonrobust

{(1, 2): (21,
  None,
  -0.004146461884523535,
  0.002200252892290602,
  array([46259,  6212]))}

In [51]:
def plot_bt_scores(X, y, rankings, alphaN, topk, plot_title, filename_to_save):
    """
    Plots BT scores before and after data removal.
    
    Args:
    X: np.ndarray, the design matrix.
    y: np.ndarray, the response variable.
    rankings: list of tuples, (model_name, full_score, old_score, new_score)
    alphaN: int, number of dropped matches
    topk: int, number of top models to display
    plot_title: str, title of the plot
    filename_to_save: str, path to save the figure
    """
    # Extract top-k entries
    # Sorted by old_scores (index 2) in descending.
    rankings = sorted(rankings[:topk], key=lambda x: x[2], reverse=False)
    model_names = [x[0] for x in rankings[:topk]]
    old_scores = [x[2] for x in rankings[:topk]]
    new_scores = [x[3] for x in rankings[:topk]]
    num_matches_total = len(y)
    y_plot = np.arange(len(rankings[:topk]))
    offset = 0.15
    # Plot.
    # Set global font to monospace and increase default font size
    plt.rcParams.update({
        'font.family': 'monospace',
        'font.size': 14
    })

    # Plot
    plt.figure(figsize=(13, 6), dpi=250)

    # Remove top and right spines
    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Scatter
    plt.scatter(old_scores, y_plot, marker='o', color='#fb7d4d', s=96) # label='BT Score Full Data',
    # plt.scatter(new_scores, y_plot + offset, 
    #             label=f'BT Score After Dropping {alphaN} out of {num_matches_total}\n matches ({(alphaN/num_matches_total * 100):.3f}%)',
    #             marker='s', color='orange', s=72)

    # Extend x-axis limits slightly to the left and right
    min_score = min(old_scores)
    max_score = max(old_scores) # max(max(old_scores), max(new_scores))
    plt.xlim(min_score - 0.05, max_score + 0.05)

    # Annotate scores next to points
    for i in range(len(y_plot)):
        if i > len(y_plot) - 3:
            # Position the text to the left of the point
            plt.text(old_scores[i] - 0.03, y_plot[i], f'{old_scores[i]:.3f}', 
                    va='center', ha='right', fontsize=17, fontfamily='monospace', color='#e97442')
        else:
            # Position the text to the right of the point
            plt.text(old_scores[i] + 0.03, y_plot[i], f'{old_scores[i]:.3f}', 
                    va='center', ha='left', fontsize=17, fontfamily='monospace', color='#e97442')

    # Axis
    plt.xlabel('Bradley-Terry Score', fontsize=22, fontfamily='monospace')
    plt.yticks(y_plot, model_names, fontsize=19, fontfamily='monospace')
    plt.xticks(fontsize=19, fontfamily='monospace')
    # plt.title(plot_title, fontsize=22, fontfamily='monospace')
    # plt.legend(fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.4)
    plt.tight_layout()

    # Save
    plt.savefig(filename_to_save, bbox_inches='tight')
    plt.close()

In [52]:
# plot top-20 models on full chatbot arena.
filename_to_save = 'fig/top10_cba.png'
plot_title = 'Model Rankings in Chatbot Arena'
plot_bt_scores(X, y, rankings, 1, 10, plot_title, filename_to_save)

In [20]:
ks = [5, 10, 20]
results2 = {}
for k in ks:
    alphaN = 1
    chatbotA = -1
    while chatbotA == -1:
        chatbotA, chatbotB, chatbotOriginalBetaDiff, chatNewBetaDiff, chatIndices = isRankingRobust(k, alphaN, X, y, weighted = True)
        results2[(k, alphaN)] = (chatbotA, chatbotB, chatbotOriginalBetaDiff, chatNewBetaDiff, chatIndices)
        alphaN += 1

In [ ]:
results_nonrobust_2 = {k: v for k, v in results2.items() if v[0] != -1}
results_nonrobust_2

In [ ]:
# combine results_nonrobust_1 and results_nonrobust_2.
results_nonrobust = {**results_nonrobust_1, **results_nonrobust_2}
results_nonrobust
# save results as a .pkl file.
# import pickle
# with open('results/ChatbotArenaNonrobustWtd.pkl', 'wb') as f:
#     pickle.dump(results_nonrobust, f)

In [45]:
results_nonrobust

{(1, 2): (21,
  -1,
  -0.004146461884523535,
  0.002200252892290602,
  array([46259,  6212])),
 (3, 29): (6,
  61,
  0.7214777505716051,
  -0.026849342132582388,
  array([26551, 17137, 40808, 32585,  3046, 11617, 39409, 39779, 33011,
         56011, 24859, 28859, 48893, 17324, 38734, 13179, 18149, 34968,
         37289, 20538,  1308,  5210, 23104, 49522,  7020, 46358, 27533,
         48536, 40704])),
 (5, 3): (41,
  47,
  0.01376073850843107,
  -0.001148770551445799,
  array([20425, 38755, 13835])),
 (10, 1): (5,
  4,
  0.0008246616768733395,
  -0.0012153237089130853,
  array([24811])),
 (20, 1): (35,
  48,
  0.007468269893045054,
  -0.0006298890499366605,
  array([5389]))}

#### Below, we inspect the ranking flip between the first- and second-place models.

In [39]:
### Load in results.
import pickle
with open("results/ChatbotArenaNonrobustWtd.pkl", "rb") as f:
    chatBotArenaDataDropped = pickle.load(f)

In [40]:
# chatBotArena_noTies = pd.read_csv("data/chatBotArena_noTies.csv")
# chatBotArena_noTies.head()
df.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,model_pair
0,30192,gpt-4-1106-preview,gpt-4-0613,"[""Is it morally right to try to have a certain...","[""The question of whether it is morally right ...","[""As an AI, I don't have personal beliefs or o...",1,0,0,"(gpt-4-0613, gpt-4-1106-preview)"
1,53567,koala-13b,gpt-4-0613,"[""What is the difference between marriage lice...","[""A marriage license is a legal document that ...","[""A marriage license and a marriage certificat...",0,1,0,"(gpt-4-0613, koala-13b)"
2,65089,gpt-3.5-turbo-0613,mistral-medium,"[""explain function calling. how would you call...","[""Function calling is the process of invoking ...","[""Function calling is the process of invoking ...",0,0,1,"(gpt-3.5-turbo-0613, mistral-medium)"
3,96401,llama-2-13b-chat,mistral-7b-instruct,"[""How can I create a test set for a very rare ...","[""Creating a test set for a very rare category...","[""When building a classifier for a very rare c...",1,0,0,"(llama-2-13b-chat, mistral-7b-instruct)"
4,198779,koala-13b,gpt-3.5-turbo-0314,"[""What is the best way to travel from Tel-Aviv...","[""The best way to travel from Tel Aviv to Jeru...","[""The best way to travel from Tel-Aviv to Jeru...",0,1,0,"(gpt-3.5-turbo-0314, koala-13b)"

9 evals were dropped to flip model i.d. 16 and i.d. None (the reference model).

The name of these models are: 
('gpt-4-0125-preview', 0: 'gpt-4-1106-preview')

In [31]:
## Count number of games between the two models that changed ranks.
is_gpt41106_gpt40125 = (
    (df['model_a'].str.contains('gpt-4-0125-preview') & df['model_b'].str.contains('gpt-4-1106-preview')) |
    (df['model_a'].str.contains('gpt-4-1106-preview') & df['model_b'].str.contains('gpt-4-0125-preview'))
)

num_gpt41106_gpt40125 = df[is_gpt41106_gpt40125].shape[0]
print("Number of games between GPT-4-1106 and GPT-4-0125: ", num_gpt41106_gpt40125)

Number of games between GPT-4-1106 and GPT-4-0125:  134

In [11]:
# model pairs (sorted to group symmetric pairs)
df['model_pair'] = df.apply(lambda row: tuple(sorted([row['model_a'], row['model_b']])), axis=1)
df['model_pair']

0                (gpt-4-0613, gpt-4-1106-preview)
1                         (gpt-4-0613, koala-13b)
2            (gpt-3.5-turbo-0613, mistral-medium)
3         (llama-2-13b-chat, mistral-7b-instruct)
4                 (gpt-3.5-turbo-0314, koala-13b)
                           ...
57472                      (claude-1, gpt-4-0613)
57473              (claude-2.0, llama-2-13b-chat)
57474                      (alpaca-13b, claude-1)
57475                    (palm-2, tulu-2-dpo-70b)
57476    (gemini-pro-dev-api, gpt-4-1106-preview)
Name: model_pair, Length: 57477, dtype: object

In [12]:
# Count number of games per model pair
pair_counts = df['model_pair'].value_counts()

# Compute average
average_games_per_pair = pair_counts.mean()
print("Average number of games per model pair:", average_games_per_pair) # 31.90

Average number of games per model pair: 45.08

In [ ]:
# Find the win margin between 'gpt-4-0125-preview' and 'gpt-4-1106-preview'
# that is, find all games that are between the two models.
dfFlippedRanking = df[is_gpt41106_gpt40125]
## Count number of games between that 'gpt-4-0125-preview' won.
gpt40125_wins = (
    (dfFlippedRanking['model_a'].str.contains('gpt-4-0125-preview') & dfFlippedRanking['winner_model_a'] == 1) |
    (dfFlippedRanking['model_b'].str.contains('gpt-4-0125-preview') & dfFlippedRanking['winner_model_b'] == 1)
)
num_gpt40125_wins = dfFlippedRanking[gpt40125_wins].shape[0]
 # 0.5373134328358209

Proportion of games that GPT-4-0125 won:  0.26865671641791045

In [14]:
gpt41106_wins = (
    (dfFlippedRanking['model_a'].str.contains('gpt-4-1106-preview') & dfFlippedRanking['winner_model_a'] == 1) |
    (dfFlippedRanking['model_b'].str.contains('gpt-4-1106-preview') & dfFlippedRanking['winner_model_b'] == 1)
)

num_gpt41106_wins = dfFlippedRanking[gpt41106_wins].shape[0]

In [ ]:
print("Proportion of games that GPT-4-0125 won: ", num_gpt40125_wins / (num_gpt40125_wins + num_gpt41106_wins))

Proportion of games that GPT-4-0125 won:  0.5373134328358209

In [27]:
# dropping 3 points flips the 5th and 6th place models.
id_to_player[48], id_to_player[42]

('mistral-medium', 'qwen1.5-72b-chat')

#### Player involvement in dropped matches

In [77]:
chatBotArenaDataDropped

{(1, 2): (21,
  -1,
  -0.004146461884523535,
  0.002200252892290602,
  array([46259,  6212])),
 (3, 29): (6,
  61,
  0.7214777505716051,
  -0.026849342132582388,
  array([26551, 17137, 40808, 32585,  3046, 11617, 39409, 39779, 33011,
         56011, 24859, 28859, 48893, 17324, 38734, 13179, 18149, 34968,
         37289, 20538,  1308,  5210, 23104, 49522,  7020, 46358, 27533,
         48536, 40704])),
 (5, 3): (41,
  47,
  0.01376073850843107,
  -0.001148770551445799,
  array([20425, 38755, 13835])),
 (10, 1): (5,
  4,
  0.0008246616768733395,
  -0.0012153237089130853,
  array([24811])),
 (20, 1): (35,
  48,
  0.007468269893045054,
  -0.0006298890499366605,
  array([5389]))}

In [34]:
with open('/Users/JennyH/Desktop/IsRankingRobust/results/ChatbotArenaNonrobustWtd.pkl', 'rb') as f:
    chatBotArenaDataDropped = pickle.load(f)

### Manuel check (for each k) on the MIS!

In [35]:
results_nonrobust = chatBotArenaDataDropped

In [36]:
old_tuple = chatBotArenaDataDropped[(1, 2)] # = 0 # change none to -1 (gpt-4-1106-preview).
new_tuple = tuple(-1 if i == 1 and val is None else val for i, val in enumerate(old_tuple))
results_nonrobust[(1, 2)] = new_tuple

In [44]:
rows = []
for (k, aN), (playerA, playerB, original_beta_diff, new_beta_diff_refit, indices) in results_nonrobust.items():
    rows.append({
        "k-aN": (k, aN),
        "playerA": playerA + 1, # to account for the reference index.
        "playerB": playerB + 1,
        "original_beta_diff": original_beta_diff,
        "new_beta_diff_refit": new_beta_diff_refit,
        "indices": indices
    })
cba_results = pd.DataFrame(rows)
cba_results.head()

,k-aN,playerA,playerB,original_beta_diff,new_beta_diff_refit,indices
0,"(1, 2)",22,0,-0.004146,0.002200,"[46259, 6212]"
1,"(3, 29)",7,62,0.721478,-0.026849,"[26551, 17137, 40808, 32585, 3046, 11617, 3940..."
2,"(5, 3)",42,48,0.013761,-0.001149,"[20425, 38755, 13835]"
3,"(10, 1)",6,5,0.000825,-0.001215,[24811]
4,"(20, 1)",36,49,0.007468,-0.000630,[5389]

In [38]:
cba_results['indices'][0]

array([46259,  6212])

In [39]:
# reverse the mapping.
id_to_player = {v: k for k, v in player_to_id.items()}

In [40]:
id_to_player[0], id_to_player[22]

('llama-2-13b-chat', 'llama-13b')

In [47]:
# read in the results.
cba_results.head()
cba_results['playerA_Name'] = cba_results['playerA'].map(id_to_player)
cba_results['playerB_Name'] = cba_results['playerB'].map(id_to_player)

In [48]:
cba_results.head()

,k-aN,playerA,playerB,original_beta_diff,new_beta_diff_refit,indices,playerA_Name,playerB_Name
0,"(1, 2)",22,0,-0.004146,0.002200,"[46259, 6212]",gpt-4-0125-preview,gpt-4-1106-preview
1,"(3, 29)",7,62,0.721478,-0.026849,"[26551, 17137, 40808, 32585, 3046, 11617, 3940...",gpt-4-0314,mistral-7b-instruct-v0.2
2,"(5, 3)",42,48,0.013761,-0.001149,"[20425, 38755, 13835]",qwen1.5-72b-chat,mistral-medium
3,"(10, 1)",6,5,0.000825,-0.001215,[24811],gemini-pro,mixtral-8x7b-instruct-v0.1
4,"(20, 1)",36,49,0.007468,-0.000630,[5389],gpt-3.5-turbo-0314,nous-hermes-2-mixtral-8x7b-dpo

In [76]:
# for each index, find the corresponding row in the original dataframe.
indices = cba_results['indices'][0] 
rawBT.iloc[indices]
# find the proportion of games where neither

                    model_a             model_b  winner_model_a  winner_tie
46259            vicuna-13b  gpt-4-0125-preview               1           0
6212   stripedhyena-nous-7b  gpt-4-0125-preview               1           0

In [ ]:
# k=1. 2 games were dropped to flip models gpt-4-0125-preview (1st place) with gpt-4-1106-preview (2nd place). 
# all dropped matches were between gpt-4-0125-preview and vicuna-13b, and stripedhyena-nous-7b, with gpt-4-0125-preview winning.


# k=3. 29 games were dropped to flip models gpt-4-0314 (3rd place) with mistral-7b-instruct-v0.2 (6th place).
# all games were between mistral-7b-instruct-v0.2 and various other models, mistral-7b-instruct-v0.2 loses all of these matches.


# k=5. 3 games were dropped to flip models qwen1.5-72b-chat (5th place) with mistral-medium (6th place).
# all dropped matches were between qwen1.5-72b-chat and  gpt-4-1106-preview (1st place), with qwen1.5-72b-chat (5th place) winning.

# k=10. 1 game was dropped to flip models gemini-pro (10th) and mixtral-8x7b-instruct-v0.1 (11th place).
# the dropped match was between the two models, with gemini-pro winning.

# k=20. 1 games were dropped to flip models gpt-3.5-turbo-0314 (20th place) and nous-hermes-2-mixtral-8x7b-dpo (21st place).
# the dropped match is between nous-hermes-2-mixtral-8x7b-dpo (21st place) and vicuna-13b (22st place), with nous-hermes-2-mixtral-8x7b-dpo losing.

In [ ]:
# k=1. 9 games were dropped to flip models gpt-4-0125-preview (1st place) with gpt-4-1106-preview (2nd place). 
# all dropped matches were between these two models, with gpt-4-0125-preview winning.
# k=3. 24 games were dropped to flip models gpt-4-0314(2nd place) with qwen1.5-72b-chat (5th place).
# all games were between qwen1.5-72b-chat and various other models, qwen1.5-72b-chat loses all of these matches.
# k=5. 5 games were dropped to flip models qwen1.5-72b-chat (5th place) with mistral-medium (6th place).
# all dropped matches were between gpt-4-1106-preview (2nd place) and qwen1.5-72b-chat, with qwen1.5-72b-chat (5th place) winning.
# k=10. 3 games were dropped to flip models yi-34b-chat (10th) and gemini-pro (11th place).
# all dropped matches are between yi-34b-chat and gemini-pro, with yi-34b-chat winning.
# k=20. 2 games were dropped to flip models nous-hermes-2-mixtral-8x7b-dpo (20th place) and 'vicuna-33b'(21st place).
# all dropped matches are between gpt-4-1106-preview (2nd place) and nous-hermes-2-mixtral-8x7b-dpo, with nous-hermes-2-mixtral-8x7b-dpo winning.

# (namely, vicuna-33b, qwen1.5-7b-chat, tulu-2-dpo-70b, gpt-3.5-turbo-1106, llama-2-13b-chat, )

### Inspect the dropped human evals.

In [174]:
chatbot_arena_results_with_props = add_match_proportions(cba_results, chatBotArena_noTies)
chatbot_arena_results_with_props.head()

,k-aN,playerA,playerB,original_beta_diff,new_beta_diff_refit,indices,playerA_Name,playerB_Name,prop_both,prop_one,prop_neither
0,"(1, 9)",17,0,0.033658,-0.001239,"[2370, 3227, 38242, 10155, 11353, 17714, 18638...",gpt-4-0125-preview,gpt-4-1106-preview,1.0,0.0,0.0
1,"(3, 24)",7,31,0.213213,-0.007985,"[24342, 29361, 38576, 36203, 12188, 15215, 364...",gpt-4-0314,qwen1.5-72b-chat,0.0,1.0,0.0
2,"(5, 5)",31,39,0.036573,-0.006157,"[9754, 19106, 20511, 9565, 26870]",qwen1.5-72b-chat,mistral-medium,0.0,1.0,0.0
3,"(10, 3)",40,5,0.011066,-0.002069,"[16514, 601, 7082]",yi-34b-chat,gemini-pro,1.0,0.0,0.0
4,"(20, 2)",57,20,0.015632,-0.013790,"[2783, 22323]",nous-hermes-2-mixtral-8x7b-dpo,vicuna-33b,0.0,1.0,0.0

In the rank-flipping between mistral and qwen, a total of 5 evaluations where qwen played and won against gpt-4-1106-preview was enough to move its ranking to above that of mistral.

In [ ]:
# Let's investigate the responses that changed the Top-5 models.
mistral_qwen_inds = chatbot_arena_results_with_props["indices"].iloc[2]
chatBotArena_noTies.iloc[mistral_qwen_inds]

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie
9754,1051544564,qwen1.5-72b-chat,gpt-4-1106-preview,"[""\nread this content. Do not change the conte...","[""6. Use AI Writing Tools\n\nIncorporating AI ...","[""6. Use AI to Your Advantage\n\nIn this age o...",1,0,0
19106,2049273519,gpt-4-1106-preview,qwen1.5-72b-chat,"[""Which is the newest model that also contain ...","[""I'm sorry, but your question isn't clear. Wh...","[""As an AI, I don't have real-time access to u...",0,1,0
20511,2199125192,qwen1.5-72b-chat,gpt-4-1106-preview,"[""Please answer this questions in 8 sentences ...","[""1. When a legal description appears clear in...","[""1. The type of ambiguity encountered is like...",1,0,0
9565,1029897539,gpt-4-1106-preview,qwen1.5-72b-chat,"[""Is it possible to give a transformer custom ...","[""Yes, it is possible to give a transformer mo...","[""Yes, it is possible to give a transformer mo...",0,1,0
26870,2888250053,gpt-4-1106-preview,qwen1.5-72b-chat,"[""How to use Poetry to install packages in pyt...","[""Poetry is a tool for dependency management a...","[""Poetry is a dependency manager for Python th...",0,1,0

In [261]:
player_to_id

{'gpt-4-1106-preview': 0,
 'koala-13b': 1,
 'llama-2-13b-chat': 2,
 'vicuna-13b': 3,
 'mixtral-8x7b-instruct-v0.1': 4,
 'gemini-pro': 5,
 'gpt-3.5-turbo-0613': 6,
 'gpt-4-0314': 7,
 'vicuna-7b': 8,
 'chatglm3-6b': 9,
 'pplx-70b-online': 10,
 'mpt-30b-chat': 11,
 'llama2-70b-steerlm-chat': 12,
 'claude-1': 13,
 'chatglm-6b': 14,
 'claude-2.0': 15,
 'starling-lm-7b-alpha': 16,
 'gpt-4-0125-preview': 17,
 'llama-2-7b-chat': 18,
 'stablelm-tuned-alpha-7b': 19,
 'vicuna-33b': 20,
 'gpt-4-0613': 21,
 'dolphin-2.2.1-mistral-7b': 22,
 'palm-2': 23,
 'wizardlm-13b': 24,
 'claude-2.1': 25,
 'claude-instant-1': 26,
 'gpt-3.5-turbo-1106': 27,
 'oasst-pythia-12b': 28,
 'qwen-14b-chat': 29,
 'openchat-3.5': 30,
 'qwen1.5-72b-chat': 31,
 'codellama-34b-instruct': 32,
 'deepseek-llm-67b-chat': 33,
 'gpt-3.5-turbo-0125': 34,
 'pplx-7b-online': 35,
 'qwen1.5-4b-chat': 36,
 'fastchat-t5-3b': 37,
 'llama-2-70b-chat': 38,
 'mistral-medium': 39,
 'yi-34b-chat': 40,
 'zephyr-7b-beta': 41,
 'openhermes-2.5-mistral-7b': 42,
 'solar-10.7b-instruct-v1.0': 43,
 'mistral-7b-instruct': 44,
 'alpaca-13b': 45,
 'dolly-v2-12b': 46,
 'mpt-7b-chat': 47,
 'qwen1.5-7b-chat': 48,
 'tulu-2-dpo-70b': 49,
 'RWKV-4-Raven-14B': 50,
 'stripedhyena-nous-7b': 51,
 'gpt4all-13b-snoozy': 52,
 'zephyr-7b-alpha': 53,
 'wizardlm-70b': 54,
 'chatglm2-6b': 55,
 'gemini-pro-dev-api': 56,
 'nous-hermes-2-mixtral-8x7b-dpo': 57,
 'llama-13b': 58,
 'guanaco-33b': 59,
 'gpt-3.5-turbo-0314': 60,
 'falcon-180b-chat': 61,
 'mistral-7b-instruct-v0.2': 62,
 'openchat-3.5-0106': 63}

In [194]:
# MIS: prompts.
# for prompt in chatBotArena_noTies.iloc[gpt4top2_inds]['prompt']:
#     print(prompt)
import textwrap
for i, prompt in enumerate(chatBotArena_noTies.loc[mistral_qwen_inds]['prompt']):
    print(f"\n=== prompt {i+1} ===\n")
    print(textwrap.fill(prompt, width=100))

=== prompt 1 ===

["\nread this content. Do not change the content written. Add 5 more tips in the same tone of voice
and style. \nhave one be use AI \n\nHey freelance writers: Let's talk about writer's block.\n\nI
know, I know. You don't want to say it out loud. It's like \"Voldemort\" or actors saying
\"Macbeth\" out loud (that's why they call it \"The Scottish Play\"). But, like the common cold,
writer's block is out there ... and odds are, it's going to get every freelance writer at some
point.\n\nThe Terror of Writer's Block\n\nYou've probably had it happen to you at one time or
another. You're sitting at your desk, a cup of coffee or cold beverage nearby, ready to start
writing, knocking off those assignments, and adding some zeroes to the bank account. The words are
ready to go ... but somehow, someway, they just won't come out. The blank page remains there,
looking at you, taunting you.\n\nThen the terror starts. \"Oh no,\" you think. \"How long will this
last? Will I get paralyzed by writer's block? Is my writing career over? Am I going to have to find
a whole new line of work?\"\n\nIt's a feeling very specific to freelance writers, that mixture of
terror and dread that comes with writer's block. However, don't fret. Writer's block isn't
permanent. There are plenty of strategies you can employ to get over it and get back on the writing
wagon. Let's go through some of them here!\n\n5 Strategies to Get Over Writer's Block\n\nSo, how can
freelance writers get over writer's block? Here are five ways to do it.\n\n1. Take a
Break\u00a0\n\nTaking time to yourself is ALWAYS a great idea, and in this specific situation, it
can be an excellent cure for writer's block. Take a few deep breaths. Take a walk in nature. If you
have a reliable meditation application or yoga practice, take some time and do a reset. Hop in your
car and go for a drive, even if it's just to the convenience store for a soda or two.\n\n2. Write
About Something Else\n\nIt might be the subject that's blocking you up. Do some experimenting to
find out if it's just what you need to write about that's putting you in the box. Remember the
incredible story about the Coen brothers: When they got stuck while writing the movie \"Miller's
Crossing,\" they instead wrote a movie about someone with writer's block. That movie is \"Barton
Fink,\" one of their finest works. Odds are, you probably have another assignment or two coming up
OR your own type of creative writing project in a drawer somewhere. Try to shift your focus a
little, and see if that prompts anything.\n\n3. Change Your Environment\u00a0\n\nEvery writer runs
the risk of letting their environment get to them. If you're one of the many writers that do their
work in the same place every day (a desk, a couch, etc.), try to switch things up. Go to a coffee
shop (rules and regulations pending, of course), try a different part of your home, or move to a
professional environment (like a rented workspace) for the day to get your brain working. You might
be surprised what breaks the dam open.\n\n4. Defeat the Blank Page\n\nThe blank page is the most
intimidating thing in the world for a writer. It's full of promise and potential, of course, but
it's also extremely scary \u2014 there's no one else who can fill it in! It's all on you, after all.
So, fill that blank page in with something. Put in a bit of writing that inspires you. Put in a
quote that you like. Hey, even just smash your fingers on the keyboard and fill the blank screen
with absolute nonsense. After that, you can say that you started writing something, even if you
technically have written nothing toward the actual assignment. That might help!\n\n5. Remind
Yourself That You're Awesome\n\nFreelance writers, remind yourself that that's exactly what you are.
You're a writer. That's a powerful thing. A lot of people want to say that they're writers. Very few
of them actually are. You've gotten paid to put words down on paper (or the internet). That's
exceedingly rare. You're valuable, smart, intelligent, and an excellent writer. Keep saying that to
yourself. Peruse through a few assignments that got you kudos or that made you proud. Then, sit down
and realize that \"this too shall pass.\"\n\nNow, start writing!\n\nGetting Started With
Scripted\n\nIf you're one of the many freelance writers who have gone through writer's block (and
come out on the other side), or even if you're one of the lucky ones to avoid it over the years,
it's time to join Scripted! Scripted boasts the best community for writers on the web, with
excellent rates, wonderful topics to write about, and much more."]

=== prompt 2 ===

["Which is the newest model that also contain data of 2023?"]

=== prompt 3 ===

["Please answer this questions in 8 sentences and do not use wording indicative of AI\n\n1.You are
provided with a legal description that seems to make sense when you initially read\nit but once you
arrive at the site it no longer does. What type of ambiguity have you\nencountered? How would you go
about conducting retracement work with an ambiguous\ndescription? What evidence should be
collected?\n2. Original monumentation is generally treated as authoritative. Why was this not the
case in\nRichmond Hill Furriers v. Clarissa Developments?\n3. What is meant by the terms
\u201cextrinsic evidence\u201d and \u201cparol evidence\u201d? Provide an example\nof each and
explain the circumstances under which they could be used or not be used by a\ncourt in deciding on a
disputed boundary line.\n4. Under what circumstances does evidence of the subdivider\u2019s
intention become important?\nWhat types of evidence did the court use in Home Bank of Canada v.
Might Directories and\nOvens v. Davidson to show a subdivider\u2019s intention in their
decisions?\n2\n5. Excerpts from the decision in Doyle v. Macdonald are included in the Annotated
Readings as\nan example of a dispute involving differing interpretations of a metes and
bounds\ndescription in a deed. What are the key \u201ctake-aways\u201d from this case? Why is it
an\ninstructive example in the application of key principles"]

=== prompt 4 ===

["Is it possible to give a transformer custom embeddings?"]

=== prompt 5 ===

["How to use Poetry to install packages in python"]

In [195]:
# MIS: Answer ModelA.
# for response_A in chatBotArena_noTies.iloc[gpt4top2_inds]['response_a']:
#     print(response_A)
import textwrap

for i, response_a in enumerate(chatBotArena_noTies.loc[mistral_qwen_inds]['response_a']):
    print(f"\n=== Response {i+1} ===\n")
    print(textwrap.fill(response_a, width=100))

=== Response 1 ===

["6. Use AI Writing Tools\n\nIncorporating AI writing tools can occasionally help break the creative
gridlock. There are various AI assistants that can generate prompts, suggest sentences, or even
complete paragraphs for you. Of course, you'll want to maintain your unique voice and edit AI-
generated content, but it's a useful starting point to overcome writer's block. It can spark new
ideas or simply provide a gentle nudge to get your creative juices flowing.\n\n7. Engage in Physical
Exercise\n\nPhysical activity can help clear your mind and boost your energy levels. Go for a run,
hit the gym, or do a brief workout session. Exercise releases endorphins that can improve your mood
and stimulate your brain, making it easier to overcome writer's block. Plus, you'll feel refreshed
and ready to tackle your writing once you're done.\n\n8. Set Realistic Writing Goals\n\nSometimes,
the pressure of a looming deadline or an overly ambitious goal can contribute to writer's block.
Break your writing tasks into smaller, manageable chunks. Set realistic daily or hourly word count
goals, and reward yourself for reaching each milestone. This approach can help alleviate stress and
make the writing process feel more achievable.\n\n9. Connect with Fellow Writers\n\nTalking to other
writers can provide valuable insights and encouragement. Join a writing group or attend a virtual
workshop. Share your struggles with writer's block and listen to how others have dealt with it. You
might find a new approach or simply gain comfort from knowing you're not alone.\n\n10. Embrace
Imperfection\n\nRemember that your first draft doesn't have to be perfect. In fact, it's okay if
it's terrible! The beauty of writing is in the editing process. Just start writing anything that
comes to mind, even if it seems nonsensical or irrelevant. The act of getting words down on the page
can often lead to a breakthrough. You can always revise and polish later, but the most important
thing is to get started.\n\nWith these additional strategies, you'll be better equipped to conquer
writer's block and continue thriving in your freelance writing career. Happy writing!"]

=== Response 2 ===

["I'm sorry, but your question isn't clear. When you ask about the \"newest model that also contains
data of 2023,\" I need more context to provide you with an accurate answer. Are you referring to a
specific type of product or technology, such as a car, a smartphone, a computer, or something else?
Please provide more details so I can assist you effectively."]

=== Response 3 ===

["1. When a legal description appears clear initially but becomes confusing at the site, it
indicates an issue of latent ambiguity. Retracement work with such a description requires careful
examination of surrounding landmarks, historical records, and surveys. To proceed, one would consult
old deeds, plat maps, and possibly consult with experts like land surveyors. Gathering evidence like
original survey notes, photographs, and witness testimonials from neighboring landowners can help
clarify the intended boundaries.\n2. In Richmond Hill Furriers v. Clarissa Developments, original
monumentation was not treated as authoritative due to the presence of a latent ambiguity. The court
found that the developer's intentions were not clear, and the physical evidence on the ground
contradicted the survey, necessitating a reevaluation of the property lines.\n3. Extrinsic evidence
refers to information outside the legal document that can help clarify its meaning, such as witness
testimony or surrounding circumstances at the time of the deed. Parol evidence, on the other hand,
is oral evidence or testimony that explains the context of a written contract. An example of
extrinsic evidence could be a diary entry describing the intent behind a property transfer. Parol
evidence might be a witness's recollection of a conversation between the parties involved. Courts
may allow these types of evidence when the document's meaning is unclear or disputed, but they may
not be considered if the contract is deemed unambiguous.\n4. The subdivider's intention becomes
crucial when there's ambiguity in the description or when the physical monuments don't align with
the legal description. In Home Bank of Canada v. Might Directories, the court looked at the layout
of streets and lots to infer the subdivider's intent. In Ovens v. Davidson, the court considered the
logical arrangement of properties and the developer's plans to determine the boundary. These cases
demonstrate that courts can use various types of evidence, including deeds, surveys, and development
plans, to understand the subdivider's original purpose.\n5. Doyle v. Macdonald showcases the
importance of precise language and the challenges in interpreting metes and bounds descriptions. Key
takeaways include the need for clear communication, the significance of landmarks, and the court's
reliance on the intent of the original parties. This case serves as an instructive example because
it highlights the potential for disputes when descriptions are imprecise, emphasizing the importance
of accurate and detailed boundary descriptions in property transactions."]

=== Response 4 ===

["Yes, it is possible to give a transformer model custom embeddings. Transformer models typically
use an embedding layer at the input to convert token IDs into vector representations. These
embeddings can be either trained from scratch along with the model or initialized with pre-trained
embeddings such as word2vec, GloVe, or fastText.\n\nTo use custom embeddings in a transformer model,
you would typically follow these steps:\n\n1. **Prepare Custom Embeddings**: First, you'll need to
have your custom embeddings ready. These could be embeddings you've trained yourself or embeddings
from another source that you want to use with your transformer model.\n\n2. **Initialize Embedding
Layer**: When building your transformer model, you would initialize the embedding layer with your
custom embeddings. This usually involves replacing the default initialization with your pre-trained
embeddings. For example, in PyTorch, you might do something like this:\n\n```python\nimport
torch\nfrom torch.nn import Embedding\n\n# Assuming you have a pre-trained embedding matrix
'pretrained_embeddings'\n# with shape (vocab_size, embedding_dim)\nembedding_layer =
Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)\nembedding_layer.weight.data.copy_
(torch.from_numpy(pretrained_embeddings))\n```\n\n3. **Freeze Embeddings (Optional)**: Depending on
your use case, you may want to freeze the embeddings, which means they will not be updated during
training. This is common when using pre-trained embeddings that are already tuned for your task. To
freeze the embeddings in PyTorch, you would do:\n\n```python\nembedding_layer.weight.requires_grad =
False\n```\n\n4. **Integrate with Transformer**: Once you have your embedding layer set up, you can
integrate it into your transformer model architecture. Make sure to replace the default embedding
layer with your custom one.\n\n5. **Train or Fine-Tune**: You can now proceed to train or fine-tune
your transformer model with the custom embeddings. If you've chosen to freeze the embeddings, only
the rest of the model's parameters will be updated.\n\nIt's worth noting that the transformer
architecture is designed to work with embeddings of a specific dimension (the model's hidden size).
So, your custom embeddings need to match that dimension, or you will need to add a linear layer to
project them to the correct size.\n\nAlso, keep in mind that when dealing with models like BERT or
GPT, the embedding layer is often more complex, including position embeddings and token type
embeddings in addition to word embeddings. You would need to ensure that your custom embeddings are
compatible with the model's architecture."]

=== Response 5 ===

["Poetry is a tool for dependency management and packaging in Python. It allows you to declare the
libraries your project depends on and it will manage (install\/update) them for you. To use Poetry
to install packages, you need to have Poetry itself installed. If you haven't already installed
Poetry, you can do so using the following command:\n\n```bash\ncurl -sSL https:\/\/install.python-
poetry.org | python3 -\n```\n\nOr, for Windows PowerShell:\n\n```powershell\n(Invoke-WebRequest -Uri
https:\/\/install.python-poetry.org -UseBasicParsing).Content | py -\n```\n\nPlease ensure that you
have `python` and `curl` installed on your system before running these commands. After installing
Poetry, follow these steps to use it for managing dependencies:\n\n1. **Initialize a new project
with Poetry** (if you haven't already):\n   ```bash\n   poetry new my-project\n   ```\n   Replace
`my-project` with the name of your project. This will create a new directory with some basic
structure and a `pyproject.toml` file, which is used by Poetry to manage dependencies.\n\n2. **Add a
dependency**:\n   To add a new package to your project, use the `add` command:\n   ```bash\n
poetry add package-name\n   ```\n   Replace `package-name` with the name of the package you want to
install. Poetry will resolve the dependencies, download the package, and update the `pyproject.toml`
and `poetry.lock` files accordingly.\n\n3. **Install dependencies**:\n   If you have a
`pyproject.toml` file with defined dependencies, you can install all of them at once using:\n
```bash\n   poetry install\n   ```\n   This command will install all the dependencies specified in
your `pyproject.toml` file, based on the versions locked in the `poetry.lock` file to ensure
repeatability.\n\n4. **Update a dependency**:\n   To update a specific package, use the `update`
command:\n   ```bash\n   poetry update package-name\n   ```\n   Replace `package-name` with the name
of the package you want to update. To update all packages, just run `poetry update` without
specifying a package name.\n\n5. **Remove a dependency**:\n   To remove a package that you no longer
need, use the `remove` command:\n   ```bash\n   poetry remove package-name\n   ```\n   Replace
`package-name` with the name of the package you want to remove.\n\nRemember to activate the virtual
environment that Poetry has created for your project before running your Python application. You can
do this by executing `poetry shell` or by using `poetry run python yourscript.py` to run your script
within the virtual environment without manually activating it."]

In [196]:
import textwrap

for i, response_b in enumerate(chatBotArena_noTies.loc[mistral_qwen_inds]['response_b']):
    print(f"\n=== Response {i+1} ===\n")
    print(textwrap.fill(response_b, width=100))

=== Response 1 ===

["6. Use AI to Your Advantage\n\nIn this age of technology, leverage the power of AI to overcome
writer's block. AI writing tools can provide prompts, continue a thought, or even help outline your
piece. It's like having a brainstorming buddy at your fingertips, one who's available 24\/7 and
doesn't mind you bouncing ideas off of them, no matter how rough they might be. Just type in a
sentence or a theme, and let the artificial intelligence give you a nudge in the right direction.
Remember, it's not about replacing your creativity but enhancing it.\n\n7. Set Small, Achievable
Goals\n\nSometimes writer's block stems from feeling overwhelmed by the size of the project. Break
it down into small, manageable pieces. Set a goal for a paragraph, a page, or maybe just a great
opening sentence. Achieving these smaller goals can give you a sense of progress and help build
momentum. As you tick off these mini milestones, the larger project won't seem so daunting.\n\n8.
Engage in Creative Cross-Training\n\nJust like athletes cross-train to improve overall performance,
writers can benefit from flexing different creative muscles. Try your hand at poetry, flash fiction,
or even doodling. Engage in a different form of storytelling to stimulate your mind. These creative
exercises can unlock new ways of thinking and help you approach your writing blocks from fresh
angles.\n\n9. Collaborate with Other Writers\n\nReach out to your network of fellow scribes.
Sometimes, discussing your project with another writer can provide the breakthrough you need.
Collaborative brainstorming sessions, writing groups, or even online forums can offer new
perspectives and insights that help you break through the block. Plus, it's always comforting to
know you're not alone in your struggles.\n\n10. Embrace Free Writing\n\nSet a timer for 10-15
minutes and just write. Don't worry about grammar, structure, or even making sense. Just let the
words flow without judgment or the pressure of your assignment. This free writing exercise can act
as a warm-up for your brain, loosening up the mental muscles and often leading to unexpected ideas
that you can refine and use in your actual writing work."]

=== Response 2 ===

["As an AI, I don't have real-time access to updates or the ability to browse the internet for the
most recent information. My knowledge is based on the data I was trained on, which is up until 2021.
Therefore, I cannot tell you about the newest model that contains data from 2023. For the most up-
to-date information, I would recommend checking the official websites or announcements from major
technology companies or AI research institutions."]

=== Response 3 ===

["1. The type of ambiguity encountered is likely a latent ambiguity, where the description seems
clear on paper but is problematic when applied to the physical location. To conduct retracement work
with an ambiguous description, one would start by gathering all available documents related to the
property, including the original deed, any maps or surveys, and prior conveyances. Next, one would
assess physical evidence on the site, such as existing monuments, fences, or natural landmarks.
Additionally, historical evidence, like old photographs or witness testimonies, could provide
insights. The evidence collected should corroborate the written description and clarify the original
intent.\n\n2. In Richmond Hill Furriers v. Clarissa Developments, original monumentation was not
treated as authoritative because the monuments did not reflect the true intent of the parties at the
time of the original conveyance. The court may have found that the monuments were misplaced or
inaccurately represented the legal description of the property. This case illustrates that while
original monuments are generally given significant weight, their authority can be challenged if
there is compelling evidence that they do not accurately represent the agreed-upon boundaries.\n\n3.
\"Extrinsic evidence\" refers to any evidence not contained within the document itself, such as
witness testimony, maps, or other documents that help interpret the document. For example, a witness
explaining the intention behind a written contract. \"Parol evidence\" is verbal evidence that is
not included in the written contract. An example would be a verbal agreement that precedes or
accompanies a written contract. Courts typically do not allow parol evidence to contradict or alter
a written agreement, but it may be used if the written contract is ambiguous or incomplete, or to
demonstrate fraud or a mistake.\n\n4. Evidence of the subdivider's intention becomes important when
there is ambiguity or dispute about the meaning of the subdivision plan or associated documents. In
Home Bank of Canada v. Might Directories, the court considered the wording in advertising materials
to interpret the subdivider's intention. In Ovens v. Davidson, testimony from the subdivider was
used to clarify the intent behind the subdivision's boundaries. These types of evidence help courts
determine how the original subdivider intended to divide the property.\n\n5. The key takeaways from
Doyle v. Macdonald include the importance of following the original intent in the deed's metes and
bounds description and the necessity of considering both the language of the deed and the physical
circumstances at the time of the conveyance. The case is instructive in demonstrating how courts
resolve disputes involving ambiguous descriptions by interpreting the deed within its historical
context, giving effect to the parties' intentions, and using extrinsic evidence to inform their
understanding of the property's physical features as they existed when the deed was executed."]

=== Response 4 ===

["Yes, it is possible to give a transformer model custom embeddings. In fact, this is a common
practice when fine-tuning pre-trained transformer models for specific tasks.\n\nWhen you work with a
pre-trained transformer model, such as BERT, GPT, or RoBERTa, the model already has an embedding
layer that converts input tokens into dense vectors. These embeddings are learned during the pre-
training phase on a large corpus of text. However, you can customize these embeddings in two main
ways:\n\n1. **Fixed embeddings**: If you have pre-existing embeddings for your input tokens, you can
use them as a starting point. You can replace the initial embedding layer with your custom
embeddings, keeping them fixed during fine-tuning. This approach is useful if you have domain-
specific embeddings or want to incorporate external knowledge. However, keep in mind that the rest
of the model will not be able to update these embeddings during training.\n\n2. **Fine-tunable
embeddings**: In most cases, when you fine-tune a transformer model, you allow the entire model,
including the embedding layer, to be updated during training. This means that the model can learn
task-specific embeddings based on your input data. You can initialize the embedding layer with your
custom embeddings, and the model will adjust them during the fine-tuning process.\n\nTo implement
custom embeddings, you'll need to modify the model's code or use a library that supports this
feature. For instance, if you're using Hugging Face's `Transformers` library in Python, you can
create a custom `PreTrainedModel` subclass, load your pre-trained transformer, and replace the
embedding layer with your custom one. Alternatively, you can use the `from_pretrained` method and
pass your custom embeddings as an argument.\n\nHere's an example using Hugging Face's `Transformers`
library:\n\n```python\nfrom transformers import BertModel, BertTokenizer, BertConfig\n\n# Load pre-
trained model and tokenizer\nmodel = BertModel.from_pretrained('bert-base-uncased')\ntokenizer =
BertTokenizer.from_pretrained('bert-base-uncased')\n\n# Create custom embeddings (this is a
placeholder, replace with your actual embeddings)\ncustom_embeddings =
torch.randn((tokenizer.vocab_size, model.config.hidden_size))\n\n# Replace the model's embedding
layer with custom embeddings\nmodel.bert.embeddings.word_embeddings =
nn.Embedding.from_pretrained(custom_embeddings, freeze=False)\n\n# Now, the model is ready to be
fine-tuned with your custom embeddings\n```\n\nRemember to adjust the code according to your
specific use case and custom embeddings."]

=== Response 5 ===

["Poetry is a dependency manager for Python that makes it easy to manage project dependencies and
create self-contained virtual environments. To use Poetry to install packages in a Python project,
follow these steps:\n\n1. **Install Poetry**:\n   First, you need to install Poetry on your system.
You can do this by running the following command (you may need administrative privileges):\n\n   For
Linux\/macOS:\n   ```\n   curl -sSL https:\/\/raw.githubusercontent.com\/python-
poetry\/poetry\/master\/get-poetry.py | python -\n   ```\n\n   For Windows:\n   ```\n   python -m
pip install --upgrade poetry\n   ```\n\n2. **Create a new project or navigate to an existing
one**:\n   If you're starting a new project, create a new directory for it and navigate to that
directory in your terminal. If you already have an existing project, navigate to the project's root
directory.\n\n3. **Initialize Poetry**:\n   Run the following command to initialize a new Poetry
project and create a `pyproject.toml` file:\n   ```\n   poetry init\n   ```\n\n   Follow the prompts
to set up your project's dependencies and requirements.\n\n4. **Add a package**:\n   To install a
new package, use the `poetry add` command followed by the package name. For example, to install the
`requests` package:\n   ```\n   poetry add requests\n   ```\n\n   This command will add the package
to your `pyproject.toml` file and install it in the project's virtual environment.\n\n5. **Update an
existing package**:\n   If you want to update a package to its latest version, use the `poetry
update` command followed by the package name (optional):\n   ```\n   poetry update requests\n
```\n\n   If you don't specify a package name, it will update all the packages in your
project.\n\n6. **Lock dependencies**:\n   To create a `poetry.lock` file, which ensures that the
exact versions of dependencies are used across different environments, run:\n   ```\n   poetry
lock\n   ```\n\n7. **Activate the virtual environment**:\n   To work with the installed packages in
the project, activate the virtual environment:\n   - Linux\/macOS:\n     ```\n     poetry shell\n
```\n\n   - Windows:\n     ```\n     .venv\\Scripts\\activate\n     ```\n\n   Now you're inside the
virtual environment, and you can run your Python scripts or import the installed packages.\n\n8.
**Exit the virtual environment**:\n   When you're done, exit the virtual environment by typing
`exit` in the terminal.\n\nRemember that Poetry manages the dependencies locally for each project,
so you don't need to worry about conflicts between projects."]